// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh7mobAuqVZyZWSv6FVJUtxmGom-o2QCo',
    appId: '1:993205810180:web:5f1a5aadb8d1f0601ab151',
    messagingSenderId: '993205810180',
    projectId: 'database-8fa06',
    authDomain: 'database-8fa06.firebaseapp.com',
    storageBucket: 'database-8fa06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSM8HaZf-fvG7ww7n1phvtC-obe5ResrA',
    appId: '1:993205810180:android:692caa9bbeb145861ab151',
    messagingSenderId: '993205810180',
    projectId: 'database-8fa06',
    storageBucket: 'database-8fa06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPPW-bHSM2jWDTw0RM0G-6UjqwKmJrHeg',
    appId: '1:993205810180:ios:642abb6e67be328a1ab151',
    messagingSenderId: '993205810180',
    projectId: 'database-8fa06',
    storageBucket: 'database-8fa06.appspot.com',
    iosBundleId: 'com.zeynep.flutterApp',
  );
}
